id = "dracula"
name = "Dracula"
version = "1.0.0"
schema_version = 1
authors = ["Marc Owen Rentap"]
description = "Darkened Dracula theme for Zed"
repository = "https://github.com/marcorentap/zed-dracula"
